### ISSUE TITLE
No option to remove contacts from a list. 

### ISSUE THREAD

**Issue by webgoof** [hinterlandsupplyco/RelayApp#13]
There Does not seem to be a way to edit and existing list to remove members from it. You have to start over with a whole new group.

**Comment by hinterlandcreative** [comment]
Open up the group and swipe right to delete. Hit the plus sign at the bottom to add.   
  
  
  
  

 \Tk       
  

  
  
>

**Comment by webgoof** [comment]
Yup, there it is.  I evidently missed that direction when looking for that gesture.
