### ISSUE TITLE
Jim

### ISSUE THREAD

**Issue by Jimsings** [hinterlandsupplyco/RelayApp#14]
App is easy to use and load contacts. However the main reason for it isn’t working for me. I tried sending a message to two different iPhones under the group selection and even the single selection but in both cases was able to respond from one recipient to all three.
I have an iPhone XR that is up to date.  
please help- jim

**Comment by hinterlandcreative** [comment]
Hi Jim. There are two ways to send mass text messages in the app. One is just like a standard group message with reply all and the other is no reply all.

Use the top button to send to each contact individually and your recipients will not be able to reply to all.
![IMG_E945A7C14E69-1](https://user-images.githubusercontent.com/26602171/128201605-ff7878ed-c8f7-4340-8860-eb02eba0180f.jpeg)
